basePath: /
definitions:
  Server:
    properties:
      city: {type: string}
      provider: {type: string}
      public_ip: {type: string}
      state: {type: string}
      zip_code: {type: string}
    type: object
host: 10.244.119.122:7017
info:
  contact: {email: james@esixteen.co, name: eSixteen.co }
  description: Get machine revenue stats on demand for bitcoin.
  title: RevE16
  x-21-category: utilities
  x-21-github-project-url: https://github.com/pooleja/StatsE16
  x-21-keywords: [stats, revenue, bitcoin, money, statistics]
  x-21-quick-buy: "$ 21 buy http://10.244.119.122:7017/"
  x-21-total-price: {max: 100, min: 100}
paths:
  /:
    get:
      consumes: [application/x-www-form-urlencoded]
      produces: [application/json]
      responses:
        200:
          description: Stats for the revenue of the server.
      summary: Returns stats about the device.
schemes: [http]
swagger: '2.0'
x-21-manifest-path: /manifest
