#!/bin/bash
# test buys using 21 network
echo "testing wizardfacts"
21 buy "https://mkt.21.co/pagekicker/wizard-facts-burnt_sienna/buy"
sleep 10
echo "testing nevertrump"
21 buy "https://mkt.21.co/pagekicker/nevertrump/buy"
sleep 10
#echo "testing superiorfortune"
21 buy 'https://mkt.21.co/pagekicker/superior-fortune-shamrock/fortune?key1=riddles&key2=riddles'
sleep 10
echo "testing yodaspeaks"
21 buy 'pagekicker/yoda-speaks/buy?key1=These+fish+are+tasty.'
sleep 10
echo "testing phrase2ebook"
21 buy "pagekicker/phrase2ebook-sky-blue/bookbuild?key1=Tom+Selleck" > TomSelleck.epub
sleep 10
echo "testing howdoi21"
21 buy "pagekicker/howdoi21/howdoi?options=get+bitcoin+historical+results"
