#!/bin/bash
# test buys using 21 network
21 buy "https://mkt.21.co/pagekicker/wizard-facts-burnt_sienna/buy"
sleep 10
21 buy "https://mkt.21.co/pagekicker/nevertrump/buy"
sleep 10
21 buy "http://[fcce:a977:eef0:ac6d:2715:0000:0000:0001]:5006/fortune?key1=riddles&key2=literature"
sleep 10
21 buy "http://[fcce:a977:eef0:ac6d:2715:0000:0000:0001]:5001/buy?key1=The+force+is+strong+in+this+one."
