basePath: /
definitions:
  InvalidInput:
    properties:
      error: {type: string}
    type: object
  ProcessingError:
    properties:
      error: {type: string}
    type: object
host: '[fcce:a977:eef0:ac6d:2715:0000:0000:0001]:5010'
info:
  contact: {email: fred@PageKicker.com, name: Fred Zimmerman, url: 'http://www.PageKicker.com'}
  description: Submit a key phrase and receive a 10-100 page Word document with spidered
    research on the topic.
  license: {name: PageKicker Terms of Use, url: 'http://www.pagekicker.com/index.php/terms-conditions'}
  termsOfService: http://www.pagekicker.com/index.php/terms-conditions
  title: Term Paper Factory
  version: 0.9.0
  x-21-app-image: https://cdn.filepicker.io/api/file/4Zdmi7SQ9quCXAuZp9ef
  x-21-category: entertainment
  x-21-github-profile-url: ''
  x-21-github-project-url: ''
  x-21-keywords: [literature, research, nonfiction, school, term papers, college,
    high school]
  x-21-quick-buy: $ 21 buy 'http://[fcce:a977:eef0:ac6d:2715:0000:0000:0001]:5010/buildtermpaper?key1=The+Scarlet+Letter'
    > ~/scarlet_letter.docx
  x-21-total-price: {max: 100000, min: 10000}
  x-21-usage: null
parameters:
  htmlParam:
    description: html
    in: body
    name: html
    required: true
    schema:
      properties:
        html: {type: string}
  textParam:
    description: text
    in: body
    name: text
    required: true
    schema:
      properties:
        text: {type: string}
  urlParam:
    description: url
    in: body
    name: url
    required: true
    schema:
      properties:
        url: {type: string}
schemes: [http]
swagger: '2.0'
x-21-manifest-path: /manifest
