basePath: /
definitions:
  InvalidInput:
    properties:
      error: {type: string}
    type: object
  ProcessingError:
    properties:
      error: {type: string}
    type: object
host: '[fcce:a977:eef0:ac6d:2715:0000:0000:0001]:5004'
info:
  contact: {email: fred@PageKicker.com, name: Fred Zimmerman, url: 'https://www.PageKicker.com'}
  description: Every API call returns a quote reminding your users why they should
    never, ever vote for Donald Trump. Randomly selects from more than 600 egregious
    lies, incriminating facts, and appalling quotations.
  license: {name: PageKicker Terms of Use, url: 'http://www.pagekicker.com/index.php/terms-conditions'}
  termsOfService: http://www.pagekicker.com/index.php/terms-conditions
  title: Paella Test Book Build
  version: 0.7.2
  x-21-app-image: https://cdn.filepicker.io/api/file/g9MXNe9ZRmaJstBfXFrr
  x-21-category: entertainment
  x-21-github-profile-url: ''
  x-21-github-project-url: ''
  x-21-keywords: [humor, jokes, sentiment, politics]
  x-21-quick-buy: $ 21 buy "http://[fcce:a977:eef0:ac6d:2715:0000:0000:0001]:5004/buy"
  x-21-total-price: {max: 2750, min: 2750}
  x-21-usage: null
parameters:
  htmlParam:
    description: html
    in: body
    name: html
    required: true
    schema:
      properties:
        html: {type: string}
  textParam:
    description: text
    in: body
    name: text
    required: true
    schema:
      properties:
        text: {type: string}
  urlParam:
    description: url
    in: body
    name: url
    required: true
    schema:
      properties:
        url: {type: string}
schemes: [https]
swagger: '2.0'
x-21-manifest-path: /manifest
